version: 2.1
jobs:
  setup:
    working_directory: ~/rengular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: rengular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: rengular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: ~/rengular
          paths:
            - "node_modules"
      - run:
          name: Linting
          command: npm run lint
  test:
    working_directory: ~/rengular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/rengular
      - run: npm run test simulation -- --no-watch --no-progress --browsers=ChromeHeadlessCI,FirefoxHeadlessCI
      - run: npm run test network-context -- --no-watch --no-progress --browsers=ChromeHeadlessCI,FirefoxHeadlessCI
      - run: npm run test gekijo -- --no-watch --no-progress --browsers=ChromeHeadlessCI,FirefoxHeadlessCI
      - run: npm run test primitive -- --no-watch --no-progress --browsers=ChromeHeadlessCI,FirefoxHeadlessCI

workflows:
  version: 2
  setup-test:
    jobs:
      - setup
      - test:
          requires:
            - setup
