version: 2.1
jobs:
  build:
    working_directory: ~/rengular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: rengular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: rengular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
      - run: env CHROME_BIN=/usr/bin/google-chrome npm run test simulation -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: env CHROME_BIN=/usr/bin/google-chrome npm run test network-context -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: env CHROME_BIN=/usr/bin/google-chrome npm run test gekijo -- --no-watch --no-progress --browsers=ChromeHeadlessCI
